### ISSUE TITLE
Redefinition NEB workflow

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/nomad-neb-workflows#5]
@schumannj pointed out if the initial task (i.e., `NEBWorkflow.tasks[0]`) should truly be the scf calculation or the reference image.

From the example by @u-gajera, we were considering the [0] task to be the scf, and the [1] task to be the reference image.

I think from the perspective of NEB it makes sense to take out the SCF calculation of the workflow, so that the tasks are just the images of the workflow. If you agree, I can do a quick patch on the total_energy_differences extraction.

**Furthermore**, @schumannj @u-gajera what do you think on the name of `total_energy_differences`? Do you think the name could be more specific to NEB? Sorry, but because of the accidental merge, we need to discuss this here. If you have any other feedback feel free to drop a comment on the merged branch or in here, as you prefer.

**Comment by u-gajera** [comment]
I think you can take out SCF calculation if you would like. Generally, in batteries, we start with the SCF calculation to find optimal structure before removing the ion. This kind of proves that the structures used for the NEB calculations are optimized. However, from a computational structure point of view, its correct that we dont need SCF calculation as a part of NEB structure.

**Comment by JosePizarro3** [comment]
> I think you can take out SCF calculation if you would like. Generally, in batteries, we start with the SCF calculation to find optimal structure before removing the ion. This kind of proves that the structures used for the NEB calculations are optimized. However, from a computational structure point of view, its correct that we dont need SCF calculation as a part of NEB structure.

Yes, you can always do another workflow which groups `SCF` and `NEB` as tasks[0] and [1] respectively, but for the abstract concept of "NEB" I think the previous scf calculation has no relevance.

**Comment by JosePizarro3** [comment]
@schumannj does it make sense to also connect in series all the tasks?

**Comment by u-gajera** [comment]
Anyhow, We are meeting tomorrow, so we can discuss and decide about that. In my case, I usually use the energies as series connection. And the top point are one which should be considered there. However, Julia might have different case. I will look at the example and may me let you know by tomorrow.
